[2022-05-28 15:35:33,494] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: profile_dag.fetch_profile_from_AAPL scheduled__2022-05-27T13:35:31.972585+00:00 [queued]>
[2022-05-28 15:35:33,501] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: profile_dag.fetch_profile_from_AAPL scheduled__2022-05-27T13:35:31.972585+00:00 [queued]>
[2022-05-28 15:35:33,501] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 15:35:33,501] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-28 15:35:33,501] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 15:35:33,519] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_profile_from_AAPL> on 2022-05-27 13:35:31.972585+00:00
[2022-05-28 15:35:33,521] {standard_task_runner.py:52} INFO - Started process 11422 to run task
[2022-05-28 15:35:33,526] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'profile_dag', 'fetch_profile_from_AAPL', 'scheduled__2022-05-27T13:35:31.972585+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/profile_dag.py', '--cfg-path', '/tmp/tmpxg0ca8td', '--error-file', '/tmp/tmpayn_robz']
[2022-05-28 15:35:33,527] {standard_task_runner.py:80} INFO - Job 125: Subtask fetch_profile_from_AAPL
[2022-05-28 15:35:33,590] {logging_mixin.py:109} INFO - Running <TaskInstance: profile_dag.fetch_profile_from_AAPL scheduled__2022-05-27T13:35:31.972585+00:00 [running]> on host DESKTOP-O4M0F04.localdomain
[2022-05-28 15:35:33,634] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=profile_dag
AIRFLOW_CTX_TASK_ID=fetch_profile_from_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2022-05-27T13:35:31.972585+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-27T13:35:31.972585+00:00
[2022-05-28 15:35:33,854] {logging_mixin.py:109} INFO - Successful connection to mongo db
[2022-05-28 15:35:47,642] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 11422. PIDs of all processes in the group: [11422]
[2022-05-28 15:35:47,643] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 11422
[2022-05-28 15:35:47,643] {taskinstance.py:1430} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-28 15:35:47,643] {logging_mixin.py:109} INFO - push_profile_on_datalake exception : Task received SIGTERM signal
[2022-05-28 15:35:47,643] {python.py:175} INFO - Done. Returned value was: None
[2022-05-28 15:35:47,657] {taskinstance.py:1278} INFO - Marking task as SUCCESS. dag_id=profile_dag, task_id=fetch_profile_from_AAPL, execution_date=20220527T133531, start_date=20220528T133533, end_date=20220528T133547
[2022-05-28 15:35:47,695] {process_utils.py:70} INFO - Process psutil.Process(pid=11422, status='terminated', exitcode=0, started='15:35:32') (11422) terminated with exit code 0
